github.com:
    users:
        alberkev03:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: alberkev03
